name: Build and test

on:
- push
- pull_request

env:
  BUILD_TYPE: RelWithDebInfo

jobs:

  MacOS:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install Building Dependencies
      run: CI/before_install.osx.sh

    - name: Prime ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ env.BUILD_TYPE }}
        max-size: 1000M

    - name: Configure
      run: CI/before_script.osx.sh
    - name: Build
      run: |
        cd build
        make -j $(sysctl -n hw.logicalcpu) package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenMW-0.49.0-Darwin.dmg
        path: build/OpenMW-0.49.0-Darwin.dmg

  Output-Envs:
    name: Read .env file and expose it as output
    runs-on: ubuntu-latest
    outputs:
      VCPKG_DEPS_TAG: ${{ env.VCPKG_DEPS_TAG }}
      BUILD_TYPE: ${{ env.BUILD_TYPE }}
    steps:
      - uses: actions/checkout@v4
      - run: cat "${{ github.workspace }}/CI/github.env" >> $GITHUB_ENV

